/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthedImport } from './routes/_authed'
import { Route as IndexImport } from './routes/index'
import { Route as SignUpSplatImport } from './routes/sign-up.$'
import { Route as SignInSplatImport } from './routes/sign-in.$'
import { Route as AuthedProductImport } from './routes/_authed.product'
import { Route as AuthedAppImport } from './routes/_authed.app'
import { Route as AuthedProductProductNameImport } from './routes/_authed.product.$productName'
import { Route as AuthedAppProfileImport } from './routes/_authed.app.profile'
import { Route as AuthedProductProductNameModuleModuleNameImport } from './routes/_authed.product.$productName_.module.$moduleName'
import { Route as AuthedProductProductNameModuleModuleNameLessonLessonNameImport } from './routes/_authed.product.$productName_.module.$moduleName_.lesson.$lessonName'

// Create/Update Routes

const AuthedRoute = AuthedImport.update({
  id: '/_authed',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SignUpSplatRoute = SignUpSplatImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRoute,
} as any)

const SignInSplatRoute = SignInSplatImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRoute,
} as any)

const AuthedProductRoute = AuthedProductImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedAppRoute = AuthedAppImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedProductProductNameRoute = AuthedProductProductNameImport.update({
  id: '/$productName',
  path: '/$productName',
  getParentRoute: () => AuthedProductRoute,
} as any)

const AuthedAppProfileRoute = AuthedAppProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedAppRoute,
} as any)

const AuthedProductProductNameModuleModuleNameRoute =
  AuthedProductProductNameModuleModuleNameImport.update({
    id: '/$productName_/module/$moduleName',
    path: '/$productName/module/$moduleName',
    getParentRoute: () => AuthedProductRoute,
  } as any)

const AuthedProductProductNameModuleModuleNameLessonLessonNameRoute =
  AuthedProductProductNameModuleModuleNameLessonLessonNameImport.update({
    id: '/$productName_/module/$moduleName_/lesson/$lessonName',
    path: '/$productName/module/$moduleName/lesson/$lessonName',
    getParentRoute: () => AuthedProductRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedImport
      parentRoute: typeof rootRoute
    }
    '/_authed/app': {
      id: '/_authed/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthedAppImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/product': {
      id: '/_authed/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof AuthedProductImport
      parentRoute: typeof AuthedImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatImport
      parentRoute: typeof rootRoute
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatImport
      parentRoute: typeof rootRoute
    }
    '/_authed/app/profile': {
      id: '/_authed/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthedAppProfileImport
      parentRoute: typeof AuthedAppImport
    }
    '/_authed/product/$productName': {
      id: '/_authed/product/$productName'
      path: '/$productName'
      fullPath: '/product/$productName'
      preLoaderRoute: typeof AuthedProductProductNameImport
      parentRoute: typeof AuthedProductImport
    }
    '/_authed/product/$productName_/module/$moduleName': {
      id: '/_authed/product/$productName_/module/$moduleName'
      path: '/$productName/module/$moduleName'
      fullPath: '/product/$productName/module/$moduleName'
      preLoaderRoute: typeof AuthedProductProductNameModuleModuleNameImport
      parentRoute: typeof AuthedProductImport
    }
    '/_authed/product/$productName_/module/$moduleName_/lesson/$lessonName': {
      id: '/_authed/product/$productName_/module/$moduleName_/lesson/$lessonName'
      path: '/$productName/module/$moduleName/lesson/$lessonName'
      fullPath: '/product/$productName/module/$moduleName/lesson/$lessonName'
      preLoaderRoute: typeof AuthedProductProductNameModuleModuleNameLessonLessonNameImport
      parentRoute: typeof AuthedProductImport
    }
  }
}

// Create and export the route tree

interface AuthedAppRouteChildren {
  AuthedAppProfileRoute: typeof AuthedAppProfileRoute
}

const AuthedAppRouteChildren: AuthedAppRouteChildren = {
  AuthedAppProfileRoute: AuthedAppProfileRoute,
}

const AuthedAppRouteWithChildren = AuthedAppRoute._addFileChildren(
  AuthedAppRouteChildren,
)

interface AuthedProductRouteChildren {
  AuthedProductProductNameRoute: typeof AuthedProductProductNameRoute
  AuthedProductProductNameModuleModuleNameRoute: typeof AuthedProductProductNameModuleModuleNameRoute
  AuthedProductProductNameModuleModuleNameLessonLessonNameRoute: typeof AuthedProductProductNameModuleModuleNameLessonLessonNameRoute
}

const AuthedProductRouteChildren: AuthedProductRouteChildren = {
  AuthedProductProductNameRoute: AuthedProductProductNameRoute,
  AuthedProductProductNameModuleModuleNameRoute:
    AuthedProductProductNameModuleModuleNameRoute,
  AuthedProductProductNameModuleModuleNameLessonLessonNameRoute:
    AuthedProductProductNameModuleModuleNameLessonLessonNameRoute,
}

const AuthedProductRouteWithChildren = AuthedProductRoute._addFileChildren(
  AuthedProductRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAppRoute: typeof AuthedAppRouteWithChildren
  AuthedProductRoute: typeof AuthedProductRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAppRoute: AuthedAppRouteWithChildren,
  AuthedProductRoute: AuthedProductRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthedRouteWithChildren
  '/app': typeof AuthedAppRouteWithChildren
  '/product': typeof AuthedProductRouteWithChildren
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/app/profile': typeof AuthedAppProfileRoute
  '/product/$productName': typeof AuthedProductProductNameRoute
  '/product/$productName/module/$moduleName': typeof AuthedProductProductNameModuleModuleNameRoute
  '/product/$productName/module/$moduleName/lesson/$lessonName': typeof AuthedProductProductNameModuleModuleNameLessonLessonNameRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthedRouteWithChildren
  '/app': typeof AuthedAppRouteWithChildren
  '/product': typeof AuthedProductRouteWithChildren
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/app/profile': typeof AuthedAppProfileRoute
  '/product/$productName': typeof AuthedProductProductNameRoute
  '/product/$productName/module/$moduleName': typeof AuthedProductProductNameModuleModuleNameRoute
  '/product/$productName/module/$moduleName/lesson/$lessonName': typeof AuthedProductProductNameModuleModuleNameLessonLessonNameRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/app': typeof AuthedAppRouteWithChildren
  '/_authed/product': typeof AuthedProductRouteWithChildren
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/_authed/app/profile': typeof AuthedAppProfileRoute
  '/_authed/product/$productName': typeof AuthedProductProductNameRoute
  '/_authed/product/$productName_/module/$moduleName': typeof AuthedProductProductNameModuleModuleNameRoute
  '/_authed/product/$productName_/module/$moduleName_/lesson/$lessonName': typeof AuthedProductProductNameModuleModuleNameLessonLessonNameRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/app'
    | '/product'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/app/profile'
    | '/product/$productName'
    | '/product/$productName/module/$moduleName'
    | '/product/$productName/module/$moduleName/lesson/$lessonName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/app'
    | '/product'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/app/profile'
    | '/product/$productName'
    | '/product/$productName/module/$moduleName'
    | '/product/$productName/module/$moduleName/lesson/$lessonName'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/app'
    | '/_authed/product'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/_authed/app/profile'
    | '/_authed/product/$productName'
    | '/_authed/product/$productName_/module/$moduleName'
    | '/_authed/product/$productName_/module/$moduleName_/lesson/$lessonName'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authed",
        "/sign-in/$",
        "/sign-up/$"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authed": {
      "filePath": "_authed.tsx",
      "children": [
        "/_authed/app",
        "/_authed/product"
      ]
    },
    "/_authed/app": {
      "filePath": "_authed.app.tsx",
      "parent": "/_authed",
      "children": [
        "/_authed/app/profile"
      ]
    },
    "/_authed/product": {
      "filePath": "_authed.product.tsx",
      "parent": "/_authed",
      "children": [
        "/_authed/product/$productName",
        "/_authed/product/$productName_/module/$moduleName",
        "/_authed/product/$productName_/module/$moduleName_/lesson/$lessonName"
      ]
    },
    "/sign-in/$": {
      "filePath": "sign-in.$.tsx"
    },
    "/sign-up/$": {
      "filePath": "sign-up.$.tsx"
    },
    "/_authed/app/profile": {
      "filePath": "_authed.app.profile.tsx",
      "parent": "/_authed/app"
    },
    "/_authed/product/$productName": {
      "filePath": "_authed.product.$productName.tsx",
      "parent": "/_authed/product"
    },
    "/_authed/product/$productName_/module/$moduleName": {
      "filePath": "_authed.product.$productName_.module.$moduleName.tsx",
      "parent": "/_authed/product"
    },
    "/_authed/product/$productName_/module/$moduleName_/lesson/$lessonName": {
      "filePath": "_authed.product.$productName_.module.$moduleName_.lesson.$lessonName.tsx",
      "parent": "/_authed/product"
    }
  }
}
ROUTE_MANIFEST_END */
